### ISSUE TITLE
MySql table names changed to upper case

### ISSUE THREAD

**Issue by skaros** [kumarvv/table2pojo#1]
Hi, I tried your code to create POJO filed from a MySql database, and noticed that it gets the table names in upper case. I dig into it a bit and realised that the problem was on this line
[ ResultSet rs = stmt.executeQuery(String.format(SQL_ALL, tableName.toUpperCase()));) {](https://github.com/kumarvv/table2pojo/blob/91f008f72aff9b7ab43455dbc1396c24c5c845ba/src/main/java/com/kumarvv/table2pojo/core/PojoWriter.java#L136)
Why do you use tableNametoUpperCase(); ?
I did remove this and it worked just fine.

**Comment by kumarvv** [comment]
Thanks, @skaros for the investigation. Database names are case insensitive normally unless they are in quotes. But this is still a good fix, please raise a PR with this if you can, and I will add you as a contributor. 

Thanks,
Vijay

**Comment by kumarvv** [comment]
Fixed with https://github.com/kumarvv/table2pojo/pull/2
